### ISSUE TITLE
No statistics available in front end despite data displaying in admin

### ISSUE THREAD

**Issue by chrisfranklin** [bruth/django-tracking2#13]
Hey,

I can see both Pageviews and Visitors in the backend but I don't get anything showing up on the frontend. It just displays:

```
Visitors
No visitor stats available

Registered Users
No registered user stats available

Pageviews
No pageview stats available
```

Do you know what might be wrong? Do I need to have a certain number of visitors before stats activate? Is it deliberately skipping the superuser account from stats generation?

Sorry to be a pest,

Cheers,

Chris

**Comment by fabiogelbcke** [comment]
I'm having a similar problem. I started using the app about 20 hours ago, and I can see the visitors and pageviews in the backend, but when I try to see them on admin, all I get is:

`Visitor tracking began on 2016-07-04 05:10:11`

No matter the end date I put. I already tried to set an end date tomorrow and 5 days from now and it hasn't helped.

It seems like it's not loading the snippet html.

I apologize if it's something I'm doing wrong and thanks for the great app :)

Cheers!
Fábio
