### ISSUE TITLE
support to django 1.8

### ISSUE THREAD

**Issue by rcorzogutierrez** [bruth/django-tracking2#51]

**Comment by corebyte** [comment]
+1

**Comment by mjschultz** [comment]
The latest version should work with django 1.8, I added django 1.8 to the Travis script and it passes in https://github.com/bruth/django-tracking2/pull/53. Are there any problems with it?

**Comment by corebyte** [comment]
and this in setup.py?

`    install_requires': [
        'django>=1.4,<1.8',
    ],`

**Comment by mjschultz** [comment]
Ah, touché. Our install process ignores that bit and we're on `Django==1.8.4`/`django-tracking2==0.2.5` so I know they work together (as far as we use the two).

I made #54 that removes that from the setup.py file and all the tests still pass.

**Comment by bruth** [comment]
Merged #54 and deployed to PyPi: https://pypi.python.org/pypi/django-tracking2/0.2.6
