### ISSUE TITLE
Race Condition in _refresh_visitor

### ISSUE THREAD

**Issue by fpruitt** [bruth/django-tracking2#55]
## Issue
Even with the best efforts to get around the possible race condition in `_refresh_visitor`, there still seems to be a chance for an error on `Visitor.save()`. In the following traceback, you can see that after the `IntegrityError` is caught, when `Visitor.objects.get(pk=session_key)` is called,  the Visitor with that key no longer exists. This means either a) the `IntegrityError` is being raised for another reason other than the assumed clashing session keys, which I can't see how that could happen, or b) There's some weird race condition in which `.save()` raises an `IntegrityError` but when we try to get the Visitor it doesn't exist yet. 

## Stacktrace
```
DoesNotExist: Visitor matching query does not exist.
  File "django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "newrelic/hooks/framework_django.py", line 331, in wrapper
    return wrapped(*args, **kwargs)
  File "tracking/middleware.py", line 141, in process_response
    visitor = self._refresh_visitor(user, request, now)
  File "tracking/middleware.py", line 98, in _refresh_visitor
    visitor = Visitor.objects.get(pk=session_key)
  File "django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 334, in get
    self.model._meta.object_name
```

## Example Context at time of error

* *ip_address*:
None
* *request*: 
WSGIRequest at 0x139752192184104
* *self*:
tracking.middleware.VisitorTrackingMiddleware object at 0x7f1a9e789cc0
* *session_key*:
'3ylrw1m7oad6fxs71mcenhxfsosnyx8o'
* *time_on_site*:
-0.004183
* *user*:
None
* *user_agent*:
'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)'
* *visit_time*:	
datetime.datetime(2015, 11, 30, 23, 13, 22, 232516, tzinfo=<UTC>)
* *visitor*:
Visitor: Visitor object

## Related Code Blocks
middleware.py, lines 140-141
```
# update/create the visitor object for this request
        visitor = self._refresh_visitor(user, request, now)
```
middleware.py, lines 90-98
```
try:
    visitor.save()
except IntegrityError:
    # there is a small chance a second response has saved this
    # Visitor already and a second save() at the same time (having
    # failed to UPDATE anything) will attempt to INSERT the same
    # session key (pk) again causing an IntegrityError
    # If this happens we'll just grab the "winner" and use that!
    visitor = Visitor.objects.get(pk=session_key)
```

## Note
This only occurs when search bots are indexing our site. I'm pretty sure that the rapid request/response cycle combined with a race condition is causing this error.

## Suggested Fix
https://github.com/bruth/django-tracking2/pull/57

**Comment by bruth** [comment]
Fixed in #57
