### ISSUE TITLE
Error: AppRegistryNotReady

### ISSUE THREAD

**Issue by otrenav** [bruth/django-tracking2#58]
I've gone through the setup step by step. However, when attempting migrations (Django 1.7), I get 
```
django.core.exceptions.AppRegistryNotReady: Models for app 'auth' haven't been imported yet.
```
Any hints as to why this is happening and how to fix it? I can't make the migrations necesary (or run the dev server). Could it be related to [this error in Tastypie](https://github.com/django-tastypie/django-tastypie/commit/102905849326bc4d7cfee6cf8dfc8e0dc7a20594)?

**Comment by bruth** [comment]
I am not really up on Django 1.7+ and therefor the new app registry. @vganshin and @mjschultz Anything you can suggest?

**Comment by mjschultz** [comment]
@otrenav can you post the list of INSTALLED_APPS for your project please?

**Comment by otrenav** [comment]
@bruth I see. Thanks, I wasn't sure if this was going to work because of the note on Django 1.7 in the README file.

@mjschultz sure, here's the list. Thanks.

```
INSTALLED_APPS = (
    # Datata
    'datata_demo',
    'datata_profile',
    'datata_santander',
    'datata_notification',
    'datata_visualization',
    'questionnaire',
    'questionnaire.page',
    'questionnaire.create',
    'questionnaire.admin_projects',

    # Third-party (pre)
    'tracking',
    'analytical',
    'crispy_forms',
    'database_files',
    'django_extensions',
    'django_admin_bootstrapped',

    'django.contrib',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party (post)
    'debug_toolbar',
    'debug_toolbar_line_profiler',
)
```

**Comment by mjschultz** [comment]
I think if you just move `'tracking'` to be in the INSTALLED_APPS list after `django.contrib.auth` it should work.

I'll see about making it more position independent, though it'll depend on how many past version of django will lose support.

**Comment by otrenav** [comment]
That solved the problem. Thank you @mjschultz.

Yes, that makes sense. Also showing specific stats on specific pages would be useful.

Again, thank you.
