### ISSUE TITLE
Update url.py  to avoid using deprecated string view argument

### ISSUE THREAD

**Issue by frankvdp** [bruth/django-tracking2#60]
Currently, in Django 1.9, tracking causes a "RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead." warning. This can easily be fixed, changing the urls.py.

**Comment by bruth** [comment]
Fixed in #61
