### ISSUE TITLE
The `stat.html` part of the front end doesn't appear

### ISSUE THREAD

**Issue by fabiogelbcke** [bruth/django-tracking2#62]
Hi!

The /tracking page isn't showing any data to me. I've input end dates and start dates and all i get is

`Visitor tracking began on 2016-07-04 05:10:11`

No matter the end date I put. I already tried to set an end date tomorrow and 5 days from now and it hasn't helped.

It seems like it's not loading the stat.html part of the page.

I apologize if it's something I'm doing wrong and thanks for the great app :)

Cheers!
Fábio

This is what the page looks like:

![screen shot 2016-07-07 at 02 52 33](https://cloud.githubusercontent.com/assets/5251445/16639311/8b53ebde-43ee-11e6-9a9b-0290d0457b05.png)

**Comment by fabiogelbcke** [comment]
It worked!

The problem was that I didn't have a `get_full_name` method in my user model, it was `full name`. As soon as I added the new method it worked.

Cheers!

**Comment by bruth** [comment]
Great!
