### ISSUE TITLE
Update Package

### ISSUE THREAD

**Issue by eoinof** [bruth/django-tracking2#63]
You should update the released package. 
Currently 0.3.1 on pypi
https://pypi.python.org/pypi/django-tracking2/0.3.1

which does not include the Django 1.10 fixes from May!

Easy enough to workaround by rolling your own urls line, but might confuse people...

**Comment by bruth** [comment]
Thanks for the heads up. Unfortunately, I have not been keeping up on Django releases 😱 so I am not sure what fixes you are referring to. If it is not too much trouble, could you submit a PR with the changes?

**Comment by eoinof** [comment]
Hmmm, I'm not sure I can submit a release in a pull request.

I added a release to my repo as an example.
https://github.com/EnergyElephant/django-tracking2/releases/tag/0.3.2

**Comment by bruth** [comment]
Oh man, sorry about that. I totally misread your initial request! Right, #61 already fixes the Django 1.10 issues. Here is the release: https://pypi.python.org/pypi/django-tracking2/0.3.2

**Comment by eoinof** [comment]
Sorry, my description might have been clearer 💃
